# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4c585931-a7c2-4540-b1da-abd77c1eb646";
    { device = "/dev/disk/by-uuid/78891f85-9988-4caa-9dff-23ed2bc5d3eb";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B15C-FF7A";
    { device = "/dev/disk/by-uuid/04F4-0F64";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

 #  fileSystems."/mnt/flash-drive" =
 #   { device = "/dev/disk/by-uuid/AEEE8375EE83351D";
 #     fsType = "ntfs";
 #   };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/214fc048-ce9c-4eea-9f3d-c3b8b648c9ef"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
